server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: credit-bank
          uri: lb://credit-bank
          predicates:
            - Path=/api/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
